const actions = {
  LOGIN_START: "LOGIN_START",
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  RESTART: "RESTART",
  BIOMETRIC_TYPE: "BIOMETRIC_TYPE",
  UPDATE_INFOR_USER: "UPDATE_INFOR_USER",
  UPDATE_ERROR: "UPDATE_ERROR",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  SAVE_DATA_SCREEN: "SAVE_DATA_SCREEN",
  CLEAN_DATA_SCREEN: "CLEAN_DATA_SCREEN",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",

  SAVE_DATA_USER: "SAVE_DATA_USER",
  SAVE_AVATAR_BASE_64: "SAVE_AVATAR_BASE_64",
  CLEAN_DATA_ALL_USER_REDUX: "CLEAN_DATA_ALL_USER_REDUX",
  CLEAR_DATA_USER: "CLEAR_DATA_USER",

  UPDATE_ESIGN_OBJECT: "UPDATE_ESIGN_OBJECT",
  UPDATE_ESIGN_STEP: "UPDATE_ESIGN_STEP",
  UPDATE_ESIGN_STATUS_MONTHLY_DUE: "UPDATE_ESIGN_STATUS_MONTHLY_DUE",
  UPDATE_ESIGN_STATUS_CHASSIS: "UPDATE_ESIGN_STATUS_CHASSIS",
  UPDATE_ESIGN_STATUS_ENGINER: "UPDATE_ESIGN_STATUS_ENGINER",
  UPDATE_ESIGN_STATUS_BANK_USER: "UPDATE_ESIGN_STATUS_BANK_USER",
  UPDATE_ESIGN_STATUS_BANK_ACCOUNT: "UPDATE_ESIGN_STATUS_BANK_ACCOUNT",
  UPDATE_ESIGN_STATUS_BANK_NAME: "UPDATE_ESIGN_STATUS_BANK_NAME",
  UPDATE_ESIGN_BASE64_FILE: "UPDATE_ESIGN_BASE64_FILE",
  UPDATE_ESIGN_USER_AGREEMENT: "UPDATE_ESIGN_USER_AGREEMENT",

  UPDATE_FIRST_TIME_CONTRACT: "UPDATE_FIRST_TIME_CONTRACT", //Show Using guild for current contract list
  ERROR_TIME_OUT: "ERROR_TIME_OUT",
  ERROR_PASSWORD_EXPIRED: "ERROR_PASSWORD_EXPIRED",
  WARNED_WILL_EXPIRED_PASSWORD: "WARNED_WILL_EXPIRED_PASSWORD",
  ERROR_TOKEN_EXPIRED: "ERROR_TOKEN_EXPIRED",
  REFRESH_ERROR_PASSWORD_EXPIRED: "REFRESH_ERROR_PASSWORD_EXPIRED",

  SPLASH_SAVE_BASE64_POLICY: "SPLASH_SAVE_BASE64_POLICY",
  SPLASH_SAVE_BASE64_POLICY_ESIGN: "SPLASH_SAVE_BASE64_POLICY_ESIGN",

  //Using for login by phone
  REGISTER_BY_PHONE_SHOW_REGISTER_OPTION: "REGISTER_BY_PHONE_SHOW_REGISTER_OPTION",
  REGISTER_BY_PHONE_LOGIN_SUCCESS: "REGISTER_BY_PHONE_LOGIN_SUCCESS",
  REGISTER_BY_PHONE_LOGOUT: "REGISTER_BY_PHONE_LOGOUT",

  //Update notification
  UPDATE_READ_ALL_NOTIFICATION: "UPDATE_READ_ALL_NOTIFICATION",

};
export default actions;
